import React from "react";
import { action } from "@storybook/addon-actions";

import PlanCard from "components/ui/PlanCard";

export default {
  title: "Design System/PlanCard",
  component: PlanCard,
};

const Template = (args) => (
  <div style={{ marginTop: 30, width: 832, maxWidth: "100%", margin: "auto" }}>
    <PlanCard {...args} />
  </div>
);

const MobileTemplate = (args) => (
  <div style={{ marginTop: 30, width: 375, maxWidth: "100%", margin: "auto" }}>
    <PlanCard {...args} />
  </div>
);

export const PlanCardMedicareAdvantagePartD = Template.bind({});
PlanCardMedicareAdvantagePartD.args = {
  planData: {
    PlanName: "Medicare Prime and Complete",
    LogoURL: "",
    CarrierName: "HealthPartners",
    MedicalPremium: 25.2,
    MedicalDeductible: 0,
    MaximumOutOfPocketCost: 50,
    DrugDeductible: 20,
    EstimatedAnnualDrugCostPartialYear: 250,
    id: "planID",
    contractID: "string",
    planSubType: "string",
    planType: 3,
    PlanRating: 3.5,
    annualPlanPremium: 245,
    estimatedAnnualDrugCost: 0,
    estimatedAnnualMedicalCost: 0,
    medicalDeductible: 0,
    maximumOutOfPocketCost: 0,
    outOfNetworkMaximumOutOfPocketCost: 0,
    providers: [
      {
        firstName: "Lebron",
        lastName: "James",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Cleveland",
          state: "OH",
          streetLine1: "1818 Fake St.",
          zipCode: "12356",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Justin",
        lastName: "Herbert",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1 Championship Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Ladainian",
        lastName: "Tomlinson",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1818 Melrose Place Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Michael",
        lastName: "Scott",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: false,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "123 Wagner Way",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
    ],
    pharmacyCosts: [
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "CVS",
        address1: "123 Pharmacy Rd",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: true,
        hasCeilingPrice: true,
      },
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "Walgreens",
        address1: "123 Other Pharmacy Lane",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: false,
        hasCeilingPrice: true,
      },
    ],
    planBenefits: [
      {
        name: "string",
        description: "string",
        type: "string",
        range: [
          {
            rangeMax: 0,
            rangeMin: 0,
            amount: 0,
            amountType: 0,
          },
        ],
      },
    ],
    planDocuments: [
      {
        name: "string",
        url: "string",
        linkName: "string",
      },
    ],
    planDrugCoverage: [
      {
        tierNumber: 0,
        hasQuantityLimit: true,
        hasStepTherapy: true,
        hasPriorAuthorization: true,
        labelName: "string",
        ndc: "string",
        limitedAccess: true,
      },
    ],
    effectiveEndDate: "2021-09-07T17:41:12.304Z",
    effectiveStartDate: "2021-09-07T17:41:12.304Z",
  },
  onDetailsClick: action("details"),
  onEnrollClick: action("enroll"),
  effectiveDate: "January 2022",
  isMobile: false,
};

export const PlanCardMedicareAdvantage = Template.bind({});
PlanCardMedicareAdvantage.args = {
  planData: {
    PlanName: "Medicare Prime and Complete",
    LogoURL: "",
    CarrierName: "HealthPartners",
    MedicalPremium: 25.2,
    MedicalDeductible: 0,
    MaximumOutOfPocketCost: 50,
    DrugDeductible: 20,
    EstimatedAnnualDrugCostPartialYear: 250,
    carrierName: "HealthPartners",
    id: "planID",
    planName: "Medicare Prime and Complete",
    contractID: "string",
    planSubType: "string",
    planType: 2,
    PlanRating: 2.5,
    annualPlanPremium: 245,
    estimatedAnnualDrugCost: 0,
    estimatedAnnualMedicalCost: 0,
    medicalDeductible: 0,
    maximumOutOfPocketCost: 0,
    outOfNetworkMaximumOutOfPocketCost: 0,
    providers: [
      {
        firstName: "Lebron",
        lastName: "James",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Cleveland",
          state: "OH",
          streetLine1: "1818 Fake St.",
          zipCode: "12356",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Justin",
        lastName: "Herbert",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1 Championship Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Ladainian",
        lastName: "Tomlinson",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1818 Melrose Place Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Michael",
        lastName: "Scott",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: false,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "123 Wagner Way",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
    ],
    pharmacyCosts: [
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "CVS",
        address1: "123 Pharmacy Rd",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: true,
        hasCeilingPrice: true,
      },
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "Walgreens",
        address1: "123 Other Pharmacy Lane",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: false,
        hasCeilingPrice: true,
      },
    ],
    planBenefits: [
      {
        name: "string",
        description: "string",
        type: "string",
        range: [
          {
            rangeMax: 0,
            rangeMin: 0,
            amount: 0,
            amountType: 0,
          },
        ],
      },
    ],
    planDocuments: [
      {
        name: "string",
        url: "string",
        linkName: "string",
      },
    ],
    planDrugCoverage: [
      {
        tierNumber: 0,
        hasQuantityLimit: true,
        hasStepTherapy: true,
        hasPriorAuthorization: true,
        labelName: "string",
        ndc: "string",
        limitedAccess: true,
      },
    ],
    effectiveEndDate: "2021-09-07T17:41:12.304Z",
    effectiveStartDate: "2021-09-07T17:41:12.304Z",
  },
  onDetailsClick: action("details"),
  onEnrollClick: action("enroll"),
  effectiveDate: "January 2022",
  isMobile: false,
};

export const PlanCardMedicarePrescriptionDrugPlan = Template.bind({});
PlanCardMedicarePrescriptionDrugPlan.args = {
  planData: {
    PlanName: "Medicare Prime and Complete",
    LogoURL: "",
    CarrierName: "HealthPartners",
    MedicalPremium: 25.2,
    MedicalDeductible: 0,
    MaximumOutOfPocketCost: 50,
    DrugDeductible: 20,
    EstimatedAnnualDrugCostPartialYear: 250,
    carrierName: "HealthPartners",
    id: "planID",
    planName: "Medicare Prime and Complete",
    contractID: "string",
    planSubType: "string",
    planType: 1,
    PlanRating: 4.5,
    annualPlanPremium: 245,
    estimatedAnnualDrugCost: 0,
    estimatedAnnualMedicalCost: 0,
    medicalDeductible: 0,
    maximumOutOfPocketCost: 0,
    outOfNetworkMaximumOutOfPocketCost: 0,
    providers: [
      {
        firstName: "Lebron",
        lastName: "James",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Cleveland",
          state: "OH",
          streetLine1: "1818 Fake St.",
          zipCode: "12356",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Justin",
        lastName: "Herbert",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1 Championship Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Ladainian",
        lastName: "Tomlinson",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1818 Melrose Place Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Michael",
        lastName: "Scott",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: false,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "123 Wagner Way",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
    ],
    pharmacyCosts: [
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "CVS",
        address1: "123 Pharmacy Rd",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: true,
        hasCeilingPrice: true,
      },
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "Walgreens",
        address1: "123 Other Pharmacy Lane",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: false,
        hasCeilingPrice: true,
      },
    ],
    planBenefits: [
      {
        name: "string",
        description: "string",
        type: "string",
        range: [
          {
            rangeMax: 0,
            rangeMin: 0,
            amount: 0,
            amountType: 0,
          },
        ],
      },
    ],
    planDocuments: [
      {
        name: "string",
        url: "string",
        linkName: "string",
      },
    ],
    planDrugCoverage: [
      {
        tierNumber: 0,
        hasQuantityLimit: true,
        hasStepTherapy: true,
        hasPriorAuthorization: true,
        labelName: "string",
        ndc: "string",
        limitedAccess: true,
      },
    ],
    effectiveEndDate: "2021-09-07T17:41:12.304Z",
    effectiveStartDate: "2021-09-07T17:41:12.304Z",
  },
  onDetailsClick: action("details"),
  onEnrollClick: action("enroll"),
  effectiveDate: "January 2022",
  isMobile: false,
};

export const MobilePlanCardMedicareAdvantagePartD = MobileTemplate.bind({});
MobilePlanCardMedicareAdvantagePartD.args = {
  planData: {
    PlanName: "Medicare Prime and Complete",
    LogoURL: "",
    CarrierName: "HealthPartners",
    MedicalPremium: 25.2,
    MedicalDeductible: 0,
    MaximumOutOfPocketCost: 50,
    DrugDeductible: 20,
    EstimatedAnnualDrugCostPartialYear: 250,
    carrierName: "HealthPartners",
    id: "planID",
    planName: "Medicare Prime and Complete",
    contractID: "string",
    planSubType: "string",
    planType: 3,
    PlanRating: 4.5,
    annualPlanPremium: 245,
    estimatedAnnualDrugCost: 0,
    estimatedAnnualMedicalCost: 0,
    medicalDeductible: 0,
    maximumOutOfPocketCost: 0,
    outOfNetworkMaximumOutOfPocketCost: 0,
    providers: [
      {
        firstName: "Lebron",
        lastName: "James",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Cleveland",
          state: "OH",
          streetLine1: "1818 Fake St.",
          zipCode: "12356",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Justin",
        lastName: "Herbert",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1 Championship Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Ladainian",
        lastName: "Tomlinson",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: true,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "1818 Melrose Place Drive",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
      {
        firstName: "Michael",
        lastName: "Scott",
        degree: "MD",
        specialty: "PCP",
        npi: "string",
        isPrimary: true,
        addressId: "string",
        inNetwork: false,
        address: {
          city: "Los Angeles",
          state: "CA",
          streetLine1: "123 Wagner Way",
          zipCode: "90210",
          phoneNumbers: ["string"],
        },
      },
    ],
    pharmacyCosts: [
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "CVS",
        address1: "123 Pharmacy Rd",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: true,
        hasCeilingPrice: true,
      },
      {
        pharmacyType: 0,
        specifiedPharmacy: true,
        pharmacyID: "string",
        isMailOrder: true,
        name: "Walgreens",
        address1: "123 Other Pharmacy Lane",
        address2: "string",
        city: "string",
        zip: "string",
        state: "string",
        pharmacyPhone: "string",
        isPreferred: true,
        monthlyCosts: [
          {
            monthID: 0,
            totalMonthlyCost: 0,
            costPhases: "string",
            costDetail: [
              {
                fullCost: 0,
                memberCost: 0,
                phase: "string",
                labelName: "string",
              },
            ],
          },
        ],
        drugCosts: [
          {
            labelName: "string",
            quantity: 0,
            fullCost: 0,
            deductible: 0,
            beforeGap: 0,
            gap: 0,
            afterGap: 0,
            drugFootnotes: [
              {
                number: 0,
                letter: "string",
                description: "string",
              },
            ],
          },
        ],
        isNetwork: false,
        hasCeilingPrice: true,
      },
    ],
    planBenefits: [
      {
        name: "string",
        description: "string",
        type: "string",
        range: [
          {
            rangeMax: 0,
            rangeMin: 0,
            amount: 0,
            amountType: 0,
          },
        ],
      },
    ],
    planDocuments: [
      {
        name: "string",
        url: "string",
        linkName: "string",
      },
    ],
    planDrugCoverage: [
      {
        tierNumber: 0,
        hasQuantityLimit: true,
        hasStepTherapy: true,
        hasPriorAuthorization: true,
        labelName: "string",
        ndc: "string",
        limitedAccess: true,
      },
    ],
    effectiveEndDate: "2021-09-07T17:41:12.304Z",
    effectiveStartDate: "2021-09-07T17:41:12.304Z",
  },
  onDetailsClick: action("details"),
  onEnrollClick: action("enroll"),
  effectiveDate: "January 2022",
  isMobile: true,
};
