# CSP notes:
# GTM / GA related (blergh! removing GTM would probably allow the removal of all of this):  'unsafe-eval' 'unsafe-inline' *.google-analytics.com *.googletagmanager.com *.licdn.com *.facebook.net *.facebook.com *.linkedin.com *.adsymptotic.com
# AEPortal API calls + 'self' hosted assets (required): *.integritymarketinggroup.com *.medicarecenter.com *.sentry.io
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests; default-src 'self' 'unsafe-eval' 'unsafe-inline' *.integritymarketinggroup.com *.medicarecenter.com *.sentry.io *.google-analytics.com *.googletagmanager.com *.licdn.com *.facebook.net *.facebook.com *.linkedin.com *.adsymptotic.com; object-src 'none'; frame-ancestors 'self'; style-src 'self' fonts.googleapis.com; font-src fonts.gstatic.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set non-sensitive env variables
# that live across all envs for simplicity here
# all URIs and env specif configs live in the netlify enviornment UI configs
[build.environment]
  REACT_APP_AUTH_CLIENT_ID="AEPortal"
  REACT_APP_AUTH_SCOPES="openid profile email IdentityServerApi LeadsAPI_Full phone"
  REACT_APP_AUTH_RESPONSE_TYPE="code"
  REACT_APP_RESOURCES_URL="https://learningcenter.tawebhost.com"

# custom prebuild plugin to set version number ENV var from package.json
[[plugins]]
  package = "./plugins/netlify/prebuild-set-version-number"

# sentry build plugin
[[plugins]]
  package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
    sentryOrg = "integrity-marketing-org"
    sentryProject = "ae-agent-portal"

# Sentry is enabled for develop, qa, stage, prod
# Since all sites have the context of 'production' for each release
# error scoping is controlled with the REACT_APP_BUILD_ENV variable
# (to remove sentry errors from branch or preview deployments)
[context.production.environment]
  REACT_APP_SENTRY_DSN = "https://86b930f07e574397aa97843af29bd366@o417296.ingest.sentry.io/5316442"
  REACT_APP_SENTRY_AUTH_DSN = "https://788e98ba6d4b4114adaa443bbf8a49bc@o417296.ingest.sentry.io/5408350"
