[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
    sentryOrg = "integrity-marketing-org"
    sentryProject = "ae-agent-portal"

# Custom browserstack integration
# [[plugins]]
#  package = "/tests/conf/netlify-browserstack-plugin"

# Note, sentry is enabled for develop, qa, stage, prod
# since all sites have the context of 'production' for each release
# error scoping is controlled with the REACT_APP_BUILD_ENV variable
[context.production.environment]
  REACT_APP_SENTRY_DSN = "https://86b930f07e574397aa97843af29bd366@o417296.ingest.sentry.io/5316442"
