[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  # optional, defaults to scanning the current built version of the site
  # audit_url = 'https://www.my-custom-site.com'
  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.85
    accessibility = 0.85
    best-practices = 0.85
    seo = 0.75
    pwa = 0.5

# [[plugins]]
#   package = "@sentry/netlify-build-plugin"

#   [plugins.inputs]
#     sentryOrg = ""
#     sentryProject = ""
