[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  # optional, defaults to scanning the current built version of the site
  # audit_url = "https://www.my-custom-site.com"
  # optional, fails build when a category is below a threshold
  # temporaryily downgrading performance to pass build
  [plugins.inputs.thresholds]
    performance = 0.5
    accessibility = 0.85
    best-practices = 0.85
    seo = 0.75
    pwa = 0.5

[[plugins]]
  package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
    sentryOrg = "integrity-marketing-org"
    sentryProject = "ae-agent-portal"

# Custom browserstack integration
# [[plugins]]
#  package = "/tests/conf/netlify-browserstack-plugin"

# Note, sentry is enabled for develop, qa, stage, prod
# since all sites have the context of 'production' for each release
# error scoping is controlled with the REACT_APP_BUILD_ENV variable
[context.production.environment]
  REACT_APP_SENTRY_DSN = "https://86b930f07e574397aa97843af29bd366@o417296.ingest.sentry.io/5316442"

# temporarily adding for testing
# remove later w/ long-term config
[context.branch-deploy.environment]
  REACT_APP_SENTRY_DSN = "https://86b930f07e574397aa97843af29bd366@o417296.ingest.sentry.io/5316442"
  REACT_APP_AUTH_AUTHORITY="https://ae-identityservice-container.azurewebsites.net"
  REACT_APP_AUTH_CLIENT_ID="AEPortal"
  REACT_APP_AUTH_LOGOFF_REDIRECT_URI="https://ae-agent-portal-develop.netlify.app/signout-oidc"
  REACT_APP_AUTH_REDIRECT_URI="https://ae-agent-portal-develop.netlify.app/signin-oidc"
  REACT_APP_AUTH_LOGOFF_URL="https://ae-identityservice-container.azurewebsites.net/Account/Logout"
  REACT_APP_AUTH_SCOPES="openid profile email name"
  REACT_APP_AUTH_RESPONSE_TYPE="code"
