class PlansService {
  searchPlans = async () => {
    // TODO: integrate with the API once ready
    return {
      MedicarePlans: [
        {
          ID: "string",
          ContractID: "string",
          PlanID: "string",
          SegmentID: "string",
          PlanType: 0,
          PlanSubType: "string",
          PlanYear: "string",
          PlanName: "string",
          CarrierName: "string",
          PlanRating: 0,
          MedicalRating: 0,
          DrugRating: 0,
          AnnualPlanPremium: 0,
          AnnualCalculatedPlanPremium: 0,
          EstimatedAnnualDrugCost: 0,
          EstimatedAnnualMedicalCost: 0,
          MailOrderAnnualCost: 0,
          DrugDeductible: 0,
          DrugPremium: 0,
          MaximumOutOfPocketCost: 0,
          MedicalDeductible: 0,
          MedicalPremium: 0,
          InitialCoverageLimit: 0,
          PlanDataFields: [
            {
              Name: "string",
              Description: "string",
              Type: "string",
              BenefitId: 0,
              Range: [
                {
                  RangeMax: 0,
                  RangeMin: 0,
                  Amount: 0,
                  AmountType: 0,
                },
              ],
            },
          ],
          PlanTiers: [
            {
              PharmacyType: 0,
              TierInformation: [
                {
                  Description: "string",
                  Amount: "string",
                  TierNumber: 0,
                },
              ],
              DaysSupply: 0,
            },
          ],
          PharmacyCosts: [
            {
              PharmacyType: 0,
              SpecifiedPharmacy: true,
              PharmacyID: "string",
              IsPreferred: true,
              MonthlyCosts: [
                {
                  MonthID: 0,
                  TotalMonthlyCost: 0,
                  CostPhases: "string",
                  CostDetail: [
                    {
                      FullCost: 0,
                      MemberCost: 0,
                      Phase: "string",
                      LabelName: "string",
                    },
                  ],
                },
              ],
              DrugCosts: [
                {
                  LabelName: "string",
                  Quantity: 0,
                  FullCost: 0,
                  Deductible: 0,
                  BeforeGap: 0,
                  Gap: 0,
                  AfterGap: 0,
                  DrugFootnotes: [
                    {
                      Number: 0,
                      Letter: "string",
                      Description: "string",
                    },
                  ],
                },
              ],
              IsNetwork: true,
              HasCeilingPrice: true,
            },
          ],
          Documents: [
            {
              Types: [
                {
                  Name: "string",
                },
              ],
              Name: "string",
              Url: "string",
              LinkName: "string",
            },
          ],
          EstimatedAnnualDrugCostPartialYear: 0,
          EstimatedAnnualMailOrderDrugCostPartialYear: 0,
          EstimatedAnnualMedicalCostPartialYear: 0,
          AllowCostSharingReduction: true,
          ApplicationFee: 0,
          BrandName: "string",
          CatastrophicLimit: 0,
          CoInsurance: 0,
          CombinedDeductibleCombined: 0,
          CombinedDeductibleInNetwork: 0,
          CombinedDeductibleOutOfNetwork: 0,
          CombinedMOOPCombined: 0,
          CombinedMOOPInNetwork: 0,
          CombinedMOOPOutOfNetwork: 0,
          CSRLevel: 0,
          EffectiveEndDate: "2021-08-11T16:08:04.808Z",
          EffectiveStartDate: "2021-08-11T16:08:04.808Z",
          ExtendedPlanDetails: [
            {
              HeaderType: 0,
              SectionDetails: [
                {
                  Description: "string",
                  DetailID: 0,
                  FileSize: "string",
                  IsEnrollLink: true,
                  isExternalLink: true,
                  IsOutOfNetwork: true,
                  IsPharmacyDoc: true,
                  IsValueAddedBenefit: true,
                  LinkName: "string",
                  NumberOfPages: "string",
                  Tags: [
                    {
                      Name: "string",
                      Value: "string",
                    },
                  ],
                  Types: [
                    {
                      Name: "string",
                    },
                  ],
                  TypeID: 0,
                  Value: "string",
                  ValueTypeID: 0,
                },
              ],
              SectionID: 0,
            },
          ],
          ExternalID: "string",
          ExternalPlanID: "string",
          ExternalSegmentID: "string",
          ExtraData: [
            {
              Name: "string",
              Value: "string",
            },
          ],
          HasDrugCoverage: true,
          HasMailDrugBenefits: true,
          HasPreferredMailPharmacyNetwork: true,
          HasPreferredPharmacyNetwork: true,
          HasPreferredRetailPharmacyNetwork: true,
          IsAvailableNationwide: true,
          IsHSAQualifiedPlan: true,
          MetalID: 0,
          MetalName: "string",
          ModifiedDate: "2021-08-11T16:08:04.808Z",
          OrganizationName: "string",
          PlanTypeAbbreviation: "string",
          PlanTypeDescription: "string",
          ProductName: "string",
          ProviderURL: "string",
          RatingArea: "string",
          FormularyExternalID: "string",
          FormularyVersion: "string",
          PlanDrugCoverage: [
            {
              TierNumber: 0,
              TierDescription: "string",
              HasQuantityLimit: true,
              HasStepTherapy: true,
              HasPriorAuthorization: true,
              QuantityLimitAmount: 0,
              QuantityLimitDays: 0,
              QuantityLimitDescription: "string",
              LabelName: "string",
              NDC: "string",
              LimitedAccess: true,
            },
          ],
          ContributionType: 0,
          CalculatedMedicalPremium: 0,
          ExternalSourceDescription: "string",
          ExternalSourceID: 0,
          FormularyTiers: [
            {
              TierDescription: "string",
              TierNumber: 0,
              FormularyID: 0,
              CoveredDosages: 0,
              IsExceptionTier: true,
              CopayPrices: [
                {
                  Cost: 0,
                  CostType: 0,
                  IsMailOrder: true,
                  IsPreferredPharmacy: true,
                  DaysOfSupply: 0,
                  DefaultBenefit: true,
                },
              ],
            },
          ],
          LogoURL: "string",
          PhoneMember: "string",
          PhoneMemberTTY: "string",
          PhoneNonMember: "string",
          PhoneNonMemberTTY: "string",
          Riders: [
            {
              PlanID: "string",
              PlanName: "string",
              PlanType: 1,
              PlanSubType: "string",
              CalculatedMedicalPremium: 0,
              ApplicationFee: 0,
              CalculatedMedicalPremiumRefreshDate: "2021-08-11T16:08:04.808Z",
              HasCalculatedMedicalPremium: true,
              ExtendedPlanDetails: [
                {
                  HeaderType: 0,
                  SectionDetails: [
                    {
                      Description: "string",
                      DetailID: 0,
                      FileSize: "string",
                      IsEnrollLink: true,
                      isExternalLink: true,
                      IsOutOfNetwork: true,
                      IsPharmacyDoc: true,
                      IsValueAddedBenefit: true,
                      LinkName: "string",
                      NumberOfPages: "string",
                      Tags: [
                        {
                          Name: "string",
                          Value: "string",
                        },
                      ],
                      Types: [
                        {
                          Name: "string",
                        },
                      ],
                      TypeID: 0,
                      Value: "string",
                      ValueTypeID: 0,
                    },
                  ],
                  SectionID: 0,
                },
              ],
              PlanTypeAbbreviation: "string",
              PlanTypeDescription: "string",
              CanBeMerged: true,
              IsMergedRider: true,
              IsRequiredRider: true,
              IsWaiverStateRider: true,
              MedicalPremium: 0,
              MergedRiderIDs: [0],
              PartnerRiders: [
                {
                  IsMergePartner: true,
                  MergedRiderID: 0,
                  PartnerRiderID: 0,
                },
              ],
              ValidAdditionalRiderIDs: "string",
            },
          ],
          PreferenceMatch: 0,
          Providers: [
            {
              AddressId: "string",
              InNetwork: true,
              ProviderRecordID: 0,
              FirstName: "string",
              LastName: "string",
              MiddleName: "string",
              Suffix: "string",
              ProviderID: "string",
              NPI: "string",
              ProviderDegree: "string",
              Specialty: ["string"],
              CarrierProviderID: "string",
            },
          ],
          NonLicensedPlan: true,
          SNPType: 0,
          SNPDescription: "string",
        },
      ],
      MedigapPlans: [
        {
          ID: "string",
          ContractID: "string",
          PlanID: "string",
          SegmentID: "string",
          PlanType: 0,
          PlanSubType: "string",
          PlanYear: "string",
          PlanName: "string",
          CarrierName: "string",
          PlanRating: 0,
          MedicalRating: 0,
          DrugRating: 0,
          AnnualPlanPremium: 0,
          AnnualCalculatedPlanPremium: 0,
          EstimatedAnnualDrugCost: 0,
          EstimatedAnnualMedicalCost: 0,
          MailOrderAnnualCost: 0,
          DrugDeductible: 0,
          DrugPremium: 0,
          MaximumOutOfPocketCost: 0,
          MedicalDeductible: 0,
          MedicalPremium: 0,
          InitialCoverageLimit: 0,
          PlanDataFields: [
            {
              Name: "string",
              Description: "string",
              Type: "string",
              BenefitId: 0,
              Range: [
                {
                  RangeMax: 0,
                  RangeMin: 0,
                  Amount: 0,
                  AmountType: 0,
                },
              ],
            },
          ],
          PlanTiers: [
            {
              PharmacyType: 0,
              TierInformation: [
                {
                  Description: "string",
                  Amount: "string",
                  TierNumber: 0,
                },
              ],
              DaysSupply: 0,
            },
          ],
          PharmacyCosts: [
            {
              PharmacyType: 0,
              SpecifiedPharmacy: true,
              PharmacyID: "string",
              IsPreferred: true,
              MonthlyCosts: [
                {
                  MonthID: 0,
                  TotalMonthlyCost: 0,
                  CostPhases: "string",
                  CostDetail: [
                    {
                      FullCost: 0,
                      MemberCost: 0,
                      Phase: "string",
                      LabelName: "string",
                    },
                  ],
                },
              ],
              DrugCosts: [
                {
                  LabelName: "string",
                  Quantity: 0,
                  FullCost: 0,
                  Deductible: 0,
                  BeforeGap: 0,
                  Gap: 0,
                  AfterGap: 0,
                  DrugFootnotes: [
                    {
                      Number: 0,
                      Letter: "string",
                      Description: "string",
                    },
                  ],
                },
              ],
              IsNetwork: true,
              HasCeilingPrice: true,
            },
          ],
          Documents: [
            {
              Types: [
                {
                  Name: "string",
                },
              ],
              Name: "string",
              Url: "string",
              LinkName: "string",
            },
          ],
          EstimatedAnnualDrugCostPartialYear: 0,
          EstimatedAnnualMailOrderDrugCostPartialYear: 0,
          EstimatedAnnualMedicalCostPartialYear: 0,
          AllowCostSharingReduction: true,
          ApplicationFee: 0,
          BrandName: "string",
          CatastrophicLimit: 0,
          CoInsurance: 0,
          CombinedDeductibleCombined: 0,
          CombinedDeductibleInNetwork: 0,
          CombinedDeductibleOutOfNetwork: 0,
          CombinedMOOPCombined: 0,
          CombinedMOOPInNetwork: 0,
          CombinedMOOPOutOfNetwork: 0,
          CSRLevel: 0,
          EffectiveEndDate: "2021-08-11T16:08:04.809Z",
          EffectiveStartDate: "2021-08-11T16:08:04.809Z",
          ExtendedPlanDetails: [
            {
              HeaderType: 0,
              SectionDetails: [
                {
                  Description: "string",
                  DetailID: 0,
                  FileSize: "string",
                  IsEnrollLink: true,
                  isExternalLink: true,
                  IsOutOfNetwork: true,
                  IsPharmacyDoc: true,
                  IsValueAddedBenefit: true,
                  LinkName: "string",
                  NumberOfPages: "string",
                  Tags: [
                    {
                      Name: "string",
                      Value: "string",
                    },
                  ],
                  Types: [
                    {
                      Name: "string",
                    },
                  ],
                  TypeID: 0,
                  Value: "string",
                  ValueTypeID: 0,
                },
              ],
              SectionID: 0,
            },
          ],
          ExternalID: "string",
          ExternalPlanID: "string",
          ExternalSegmentID: "string",
          ExtraData: [
            {
              Name: "string",
              Value: "string",
            },
          ],
          HasDrugCoverage: true,
          HasMailDrugBenefits: true,
          HasPreferredMailPharmacyNetwork: true,
          HasPreferredPharmacyNetwork: true,
          HasPreferredRetailPharmacyNetwork: true,
          IsAvailableNationwide: true,
          IsHSAQualifiedPlan: true,
          MetalID: 0,
          MetalName: "string",
          ModifiedDate: "2021-08-11T16:08:04.809Z",
          OrganizationName: "string",
          PlanTypeAbbreviation: "string",
          PlanTypeDescription: "string",
          ProductName: "string",
          ProviderURL: "string",
          RatingArea: "string",
          FormularyExternalID: "string",
          FormularyVersion: "string",
          PlanDrugCoverage: [
            {
              TierNumber: 0,
              TierDescription: "string",
              HasQuantityLimit: true,
              HasStepTherapy: true,
              HasPriorAuthorization: true,
              QuantityLimitAmount: 0,
              QuantityLimitDays: 0,
              QuantityLimitDescription: "string",
              LabelName: "string",
              NDC: "string",
              LimitedAccess: true,
            },
          ],
          ContributionType: 0,
          CalculatedMedicalPremium: 0,
          ExternalSourceDescription: "string",
          ExternalSourceID: 0,
          FormularyTiers: [
            {
              TierDescription: "string",
              TierNumber: 0,
              FormularyID: 0,
              CoveredDosages: 0,
              IsExceptionTier: true,
              CopayPrices: [
                {
                  Cost: 0,
                  CostType: 0,
                  IsMailOrder: true,
                  IsPreferredPharmacy: true,
                  DaysOfSupply: 0,
                  DefaultBenefit: true,
                },
              ],
            },
          ],
          LogoURL: "string",
          PhoneMember: "string",
          PhoneMemberTTY: "string",
          PhoneNonMember: "string",
          PhoneNonMemberTTY: "string",
          Riders: [
            {
              PlanID: "string",
              PlanName: "string",
              PlanType: 1,
              PlanSubType: "string",
              CalculatedMedicalPremium: 0,
              ApplicationFee: 0,
              CalculatedMedicalPremiumRefreshDate: "2021-08-11T16:08:04.809Z",
              HasCalculatedMedicalPremium: true,
              ExtendedPlanDetails: [
                {
                  HeaderType: 0,
                  SectionDetails: [
                    {
                      Description: "string",
                      DetailID: 0,
                      FileSize: "string",
                      IsEnrollLink: true,
                      isExternalLink: true,
                      IsOutOfNetwork: true,
                      IsPharmacyDoc: true,
                      IsValueAddedBenefit: true,
                      LinkName: "string",
                      NumberOfPages: "string",
                      Tags: [
                        {
                          Name: "string",
                          Value: "string",
                        },
                      ],
                      Types: [
                        {
                          Name: "string",
                        },
                      ],
                      TypeID: 0,
                      Value: "string",
                      ValueTypeID: 0,
                    },
                  ],
                  SectionID: 0,
                },
              ],
              PlanTypeAbbreviation: "string",
              PlanTypeDescription: "string",
              CanBeMerged: true,
              IsMergedRider: true,
              IsRequiredRider: true,
              IsWaiverStateRider: true,
              MedicalPremium: 0,
              MergedRiderIDs: [0],
              PartnerRiders: [
                {
                  IsMergePartner: true,
                  MergedRiderID: 0,
                  PartnerRiderID: 0,
                },
              ],
              ValidAdditionalRiderIDs: "string",
            },
          ],
          PreferenceMatch: 0,
          Providers: [
            {
              AddressId: "string",
              InNetwork: true,
              ProviderRecordID: 0,
              FirstName: "string",
              LastName: "string",
              MiddleName: "string",
              Suffix: "string",
              ProviderID: "string",
              NPI: "string",
              ProviderDegree: "string",
              Specialty: ["string"],
              CarrierProviderID: "string",
            },
          ],
          NonLicensedPlan: true,
          SNPType: 0,
          SNPDescription: "string",
        },
      ],
      CommercialPlans: [
        {
          ID: "string",
          ContractID: "string",
          PlanID: "string",
          SegmentID: "string",
          PlanType: 0,
          PlanSubType: "string",
          PlanYear: "string",
          PlanName: "string",
          CarrierName: "string",
          PlanRating: 0,
          MedicalRating: 0,
          DrugRating: 0,
          AnnualPlanPremium: 0,
          AnnualCalculatedPlanPremium: 0,
          EstimatedAnnualDrugCost: 0,
          EstimatedAnnualMedicalCost: 0,
          MailOrderAnnualCost: 0,
          DrugDeductible: 0,
          DrugPremium: 0,
          MaximumOutOfPocketCost: 0,
          MedicalDeductible: 0,
          MedicalPremium: 0,
          InitialCoverageLimit: 0,
          PlanDataFields: [
            {
              Name: "string",
              Description: "string",
              Type: "string",
              BenefitId: 0,
              Range: [
                {
                  RangeMax: 0,
                  RangeMin: 0,
                  Amount: 0,
                  AmountType: 0,
                },
              ],
            },
          ],
          PlanTiers: [
            {
              PharmacyType: 0,
              TierInformation: [
                {
                  Description: "string",
                  Amount: "string",
                  TierNumber: 0,
                },
              ],
              DaysSupply: 0,
            },
          ],
          PharmacyCosts: [
            {
              PharmacyType: 0,
              SpecifiedPharmacy: true,
              PharmacyID: "string",
              IsPreferred: true,
              MonthlyCosts: [
                {
                  MonthID: 0,
                  TotalMonthlyCost: 0,
                  CostPhases: "string",
                  CostDetail: [
                    {
                      FullCost: 0,
                      MemberCost: 0,
                      Phase: "string",
                      LabelName: "string",
                    },
                  ],
                },
              ],
              DrugCosts: [
                {
                  LabelName: "string",
                  Quantity: 0,
                  FullCost: 0,
                  Deductible: 0,
                  BeforeGap: 0,
                  Gap: 0,
                  AfterGap: 0,
                  DrugFootnotes: [
                    {
                      Number: 0,
                      Letter: "string",
                      Description: "string",
                    },
                  ],
                },
              ],
              IsNetwork: true,
              HasCeilingPrice: true,
            },
          ],
          Documents: [
            {
              Types: [
                {
                  Name: "string",
                },
              ],
              Name: "string",
              Url: "string",
              LinkName: "string",
            },
          ],
          EstimatedAnnualDrugCostPartialYear: 0,
          EstimatedAnnualMailOrderDrugCostPartialYear: 0,
          EstimatedAnnualMedicalCostPartialYear: 0,
          AllowCostSharingReduction: true,
          ApplicationFee: 0,
          BrandName: "string",
          CatastrophicLimit: 0,
          CoInsurance: 0,
          CombinedDeductibleCombined: 0,
          CombinedDeductibleInNetwork: 0,
          CombinedDeductibleOutOfNetwork: 0,
          CombinedMOOPCombined: 0,
          CombinedMOOPInNetwork: 0,
          CombinedMOOPOutOfNetwork: 0,
          CSRLevel: 0,
          EffectiveEndDate: "2021-08-11T16:08:04.810Z",
          EffectiveStartDate: "2021-08-11T16:08:04.810Z",
          ExtendedPlanDetails: [
            {
              HeaderType: 0,
              SectionDetails: [
                {
                  Description: "string",
                  DetailID: 0,
                  FileSize: "string",
                  IsEnrollLink: true,
                  isExternalLink: true,
                  IsOutOfNetwork: true,
                  IsPharmacyDoc: true,
                  IsValueAddedBenefit: true,
                  LinkName: "string",
                  NumberOfPages: "string",
                  Tags: [
                    {
                      Name: "string",
                      Value: "string",
                    },
                  ],
                  Types: [
                    {
                      Name: "string",
                    },
                  ],
                  TypeID: 0,
                  Value: "string",
                  ValueTypeID: 0,
                },
              ],
              SectionID: 0,
            },
          ],
          ExternalID: "string",
          ExternalPlanID: "string",
          ExternalSegmentID: "string",
          ExtraData: [
            {
              Name: "string",
              Value: "string",
            },
          ],
          HasDrugCoverage: true,
          HasMailDrugBenefits: true,
          HasPreferredMailPharmacyNetwork: true,
          HasPreferredPharmacyNetwork: true,
          HasPreferredRetailPharmacyNetwork: true,
          IsAvailableNationwide: true,
          IsHSAQualifiedPlan: true,
          MetalID: 0,
          MetalName: "string",
          ModifiedDate: "2021-08-11T16:08:04.810Z",
          OrganizationName: "string",
          PlanTypeAbbreviation: "string",
          PlanTypeDescription: "string",
          ProductName: "string",
          ProviderURL: "string",
          RatingArea: "string",
          FormularyExternalID: "string",
          FormularyVersion: "string",
          PlanDrugCoverage: [
            {
              TierNumber: 0,
              TierDescription: "string",
              HasQuantityLimit: true,
              HasStepTherapy: true,
              HasPriorAuthorization: true,
              QuantityLimitAmount: 0,
              QuantityLimitDays: 0,
              QuantityLimitDescription: "string",
              LabelName: "string",
              NDC: "string",
              LimitedAccess: true,
            },
          ],
          ContributionType: 0,
          CalculatedMedicalPremium: 0,
          ExternalSourceDescription: "string",
          ExternalSourceID: 0,
          FormularyTiers: [
            {
              TierDescription: "string",
              TierNumber: 0,
              FormularyID: 0,
              CoveredDosages: 0,
              IsExceptionTier: true,
              CopayPrices: [
                {
                  Cost: 0,
                  CostType: 0,
                  IsMailOrder: true,
                  IsPreferredPharmacy: true,
                  DaysOfSupply: 0,
                  DefaultBenefit: true,
                },
              ],
            },
          ],
          LogoURL: "string",
          PhoneMember: "string",
          PhoneMemberTTY: "string",
          PhoneNonMember: "string",
          PhoneNonMemberTTY: "string",
          Riders: [
            {
              PlanID: "string",
              PlanName: "string",
              PlanType: 1,
              PlanSubType: "string",
              CalculatedMedicalPremium: 0,
              ApplicationFee: 0,
              CalculatedMedicalPremiumRefreshDate: "2021-08-11T16:08:04.811Z",
              HasCalculatedMedicalPremium: true,
              ExtendedPlanDetails: [
                {
                  HeaderType: 0,
                  SectionDetails: [
                    {
                      Description: "string",
                      DetailID: 0,
                      FileSize: "string",
                      IsEnrollLink: true,
                      isExternalLink: true,
                      IsOutOfNetwork: true,
                      IsPharmacyDoc: true,
                      IsValueAddedBenefit: true,
                      LinkName: "string",
                      NumberOfPages: "string",
                      Tags: [
                        {
                          Name: "string",
                          Value: "string",
                        },
                      ],
                      Types: [
                        {
                          Name: "string",
                        },
                      ],
                      TypeID: 0,
                      Value: "string",
                      ValueTypeID: 0,
                    },
                  ],
                  SectionID: 0,
                },
              ],
              PlanTypeAbbreviation: "string",
              PlanTypeDescription: "string",
              CanBeMerged: true,
              IsMergedRider: true,
              IsRequiredRider: true,
              IsWaiverStateRider: true,
              MedicalPremium: 0,
              MergedRiderIDs: [0],
              PartnerRiders: [
                {
                  IsMergePartner: true,
                  MergedRiderID: 0,
                  PartnerRiderID: 0,
                },
              ],
              ValidAdditionalRiderIDs: "string",
            },
          ],
          PreferenceMatch: 0,
          Providers: [
            {
              AddressId: "string",
              InNetwork: true,
              ProviderRecordID: 0,
              FirstName: "string",
              LastName: "string",
              MiddleName: "string",
              Suffix: "string",
              ProviderID: "string",
              NPI: "string",
              ProviderDegree: "string",
              Specialty: ["string"],
              CarrierProviderID: "string",
            },
          ],
          NonLicensedPlan: true,
          SNPType: 0,
          SNPDescription: "string",
        },
      ],
      AncillaryPlans: [
        {
          ID: "string",
          ContractID: "string",
          PlanID: "string",
          SegmentID: "string",
          PlanType: 0,
          PlanSubType: "string",
          PlanYear: "string",
          PlanName: "string",
          CarrierName: "string",
          PlanRating: 0,
          MedicalRating: 0,
          DrugRating: 0,
          AnnualPlanPremium: 0,
          AnnualCalculatedPlanPremium: 0,
          EstimatedAnnualDrugCost: 0,
          EstimatedAnnualMedicalCost: 0,
          MailOrderAnnualCost: 0,
          DrugDeductible: 0,
          DrugPremium: 0,
          MaximumOutOfPocketCost: 0,
          MedicalDeductible: 0,
          MedicalPremium: 0,
          InitialCoverageLimit: 0,
          PlanDataFields: [
            {
              Name: "string",
              Description: "string",
              Type: "string",
              BenefitId: 0,
              Range: [
                {
                  RangeMax: 0,
                  RangeMin: 0,
                  Amount: 0,
                  AmountType: 0,
                },
              ],
            },
          ],
          PlanTiers: [
            {
              PharmacyType: 0,
              TierInformation: [
                {
                  Description: "string",
                  Amount: "string",
                  TierNumber: 0,
                },
              ],
              DaysSupply: 0,
            },
          ],
          PharmacyCosts: [
            {
              PharmacyType: 0,
              SpecifiedPharmacy: true,
              PharmacyID: "string",
              IsPreferred: true,
              MonthlyCosts: [
                {
                  MonthID: 0,
                  TotalMonthlyCost: 0,
                  CostPhases: "string",
                  CostDetail: [
                    {
                      FullCost: 0,
                      MemberCost: 0,
                      Phase: "string",
                      LabelName: "string",
                    },
                  ],
                },
              ],
              DrugCosts: [
                {
                  LabelName: "string",
                  Quantity: 0,
                  FullCost: 0,
                  Deductible: 0,
                  BeforeGap: 0,
                  Gap: 0,
                  AfterGap: 0,
                  DrugFootnotes: [
                    {
                      Number: 0,
                      Letter: "string",
                      Description: "string",
                    },
                  ],
                },
              ],
              IsNetwork: true,
              HasCeilingPrice: true,
            },
          ],
          Documents: [
            {
              Types: [
                {
                  Name: "string",
                },
              ],
              Name: "string",
              Url: "string",
              LinkName: "string",
            },
          ],
          EstimatedAnnualDrugCostPartialYear: 0,
          EstimatedAnnualMailOrderDrugCostPartialYear: 0,
          EstimatedAnnualMedicalCostPartialYear: 0,
          AllowCostSharingReduction: true,
          ApplicationFee: 0,
          BrandName: "string",
          CatastrophicLimit: 0,
          CoInsurance: 0,
          CombinedDeductibleCombined: 0,
          CombinedDeductibleInNetwork: 0,
          CombinedDeductibleOutOfNetwork: 0,
          CombinedMOOPCombined: 0,
          CombinedMOOPInNetwork: 0,
          CombinedMOOPOutOfNetwork: 0,
          CSRLevel: 0,
          EffectiveEndDate: "2021-08-11T16:08:04.812Z",
          EffectiveStartDate: "2021-08-11T16:08:04.812Z",
          ExtendedPlanDetails: [
            {
              HeaderType: 0,
              SectionDetails: [
                {
                  Description: "string",
                  DetailID: 0,
                  FileSize: "string",
                  IsEnrollLink: true,
                  isExternalLink: true,
                  IsOutOfNetwork: true,
                  IsPharmacyDoc: true,
                  IsValueAddedBenefit: true,
                  LinkName: "string",
                  NumberOfPages: "string",
                  Tags: [
                    {
                      Name: "string",
                      Value: "string",
                    },
                  ],
                  Types: [
                    {
                      Name: "string",
                    },
                  ],
                  TypeID: 0,
                  Value: "string",
                  ValueTypeID: 0,
                },
              ],
              SectionID: 0,
            },
          ],
          ExternalID: "string",
          ExternalPlanID: "string",
          ExternalSegmentID: "string",
          ExtraData: [
            {
              Name: "string",
              Value: "string",
            },
          ],
          HasDrugCoverage: true,
          HasMailDrugBenefits: true,
          HasPreferredMailPharmacyNetwork: true,
          HasPreferredPharmacyNetwork: true,
          HasPreferredRetailPharmacyNetwork: true,
          IsAvailableNationwide: true,
          IsHSAQualifiedPlan: true,
          MetalID: 0,
          MetalName: "string",
          ModifiedDate: "2021-08-11T16:08:04.812Z",
          OrganizationName: "string",
          PlanTypeAbbreviation: "string",
          PlanTypeDescription: "string",
          ProductName: "string",
          ProviderURL: "string",
          RatingArea: "string",
          FormularyExternalID: "string",
          FormularyVersion: "string",
          PlanDrugCoverage: [
            {
              TierNumber: 0,
              TierDescription: "string",
              HasQuantityLimit: true,
              HasStepTherapy: true,
              HasPriorAuthorization: true,
              QuantityLimitAmount: 0,
              QuantityLimitDays: 0,
              QuantityLimitDescription: "string",
              LabelName: "string",
              NDC: "string",
              LimitedAccess: true,
            },
          ],
          ContributionType: 0,
          CalculatedMedicalPremium: 0,
          ExternalSourceDescription: "string",
          ExternalSourceID: 0,
          FormularyTiers: [
            {
              TierDescription: "string",
              TierNumber: 0,
              FormularyID: 0,
              CoveredDosages: 0,
              IsExceptionTier: true,
              CopayPrices: [
                {
                  Cost: 0,
                  CostType: 0,
                  IsMailOrder: true,
                  IsPreferredPharmacy: true,
                  DaysOfSupply: 0,
                  DefaultBenefit: true,
                },
              ],
            },
          ],
          LogoURL: "string",
          PhoneMember: "string",
          PhoneMemberTTY: "string",
          PhoneNonMember: "string",
          PhoneNonMemberTTY: "string",
          Riders: [
            {
              PlanID: "string",
              PlanName: "string",
              PlanType: 1,
              PlanSubType: "string",
              CalculatedMedicalPremium: 0,
              ApplicationFee: 0,
              CalculatedMedicalPremiumRefreshDate: "2021-08-11T16:08:04.812Z",
              HasCalculatedMedicalPremium: true,
              ExtendedPlanDetails: [
                {
                  HeaderType: 0,
                  SectionDetails: [
                    {
                      Description: "string",
                      DetailID: 0,
                      FileSize: "string",
                      IsEnrollLink: true,
                      isExternalLink: true,
                      IsOutOfNetwork: true,
                      IsPharmacyDoc: true,
                      IsValueAddedBenefit: true,
                      LinkName: "string",
                      NumberOfPages: "string",
                      Tags: [
                        {
                          Name: "string",
                          Value: "string",
                        },
                      ],
                      Types: [
                        {
                          Name: "string",
                        },
                      ],
                      TypeID: 0,
                      Value: "string",
                      ValueTypeID: 0,
                    },
                  ],
                  SectionID: 0,
                },
              ],
              PlanTypeAbbreviation: "string",
              PlanTypeDescription: "string",
              CanBeMerged: true,
              IsMergedRider: true,
              IsRequiredRider: true,
              IsWaiverStateRider: true,
              MedicalPremium: 0,
              MergedRiderIDs: [0],
              PartnerRiders: [
                {
                  IsMergePartner: true,
                  MergedRiderID: 0,
                  PartnerRiderID: 0,
                },
              ],
              ValidAdditionalRiderIDs: "string",
            },
          ],
          PreferenceMatch: 0,
          Providers: [
            {
              AddressId: "string",
              InNetwork: true,
              ProviderRecordID: 0,
              FirstName: "string",
              LastName: "string",
              MiddleName: "string",
              Suffix: "string",
              ProviderID: "string",
              NPI: "string",
              ProviderDegree: "string",
              Specialty: ["string"],
              CarrierProviderID: "string",
            },
          ],
          NonLicensedPlan: true,
          SNPType: 0,
          SNPDescription: "string",
        },
      ],
    };
  };
}

export default new PlansService();
