export const mockData = [
    {
        fexAttestationId: 0,
        agentId: 0,
        agentNPN: "string",
        carrierName: "string",
        displayCarrierName: "string",
        carrierId: 0,
        productNames: [
            {
                fexAttestationId: 0,
                productId: 0,
                productName: "string",
                displayproductName: "string",
            },
        ],
        producerId: "string",
        isSelfAttested: "string",
        inActive: 0,
        createDate: "2023-12-29T00:15:22.332Z",
        updateDate: "2023-12-29T00:15:22.332Z",
    },
    {
        fexAttestationId: 1,
        agentId: 0,
        agentNPN: "string",
        carrierName: "string 1",
        displayCarrierName: "string 1",
        carrierId: 0,
        productNames: [
            {
                fexAttestationId: 0,
                productId: 0,
                productName: "string 1",
                displayproductName: "string 1",
            },
        ],
        producerId: "string 1",
        isSelfAttested: "string 1",
        inActive: 0,
        createDate: "2023-12-29T00:15:22.332Z",
        updateDate: "2023-12-29T00:15:22.332Z",
    },
    {
        fexAttestationId: 2,
        agentId: 0,
        agentNPN: "string 2",
        carrierName: "string 2",
        displayCarrierName: "string 2",
        carrierId: 0,
        productNames: [
            {
                fexAttestationId: 0,
                productId: 0,
                productName: "string 2",
                displayproductName: "string 2",
            },
        ],
        producerId: "string 2",
        isSelfAttested: "string 2",
        inActive: 0,
        createDate: "2023-12-29T00:15:22.332Z",
        updateDate: "2023-12-29T00:15:22.332Z",
    },
];
