export const mockData = () => [
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "NV",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "NV",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "NV",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "NV",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "OR",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "OR",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "OR",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "BER",
    carrier: "Atrio Health Plans",
    state: "OR",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "CA",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "CA",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "FL",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "FL",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "IL",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "IL",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "MI",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "MI",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "MO",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "MO",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "VA",
    planType: "MAPD",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "NEV",
    carrier: "Essence Healthcare",
    state: "VA",
    planType: "MAPD",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "PRE",
    carrier: "Mutual Of Omaha Corp",
    state: "GA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "PRE",
    carrier: "Mutual Of Omaha Corp",
    state: "MA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "PRE",
    carrier: "Mutual Of Omaha Corp",
    state: "MS",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "PRE",
    carrier: "Mutual Of Omaha Corp",
    state: "MT",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "PRE",
    carrier: "Mutual Of Omaha Corp",
    state: "NM",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "PRE",
    carrier: "Mutual Of Omaha Corp",
    state: "PA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "1909744",
    businessUnit: "PRE",
    carrier: "Mutual Of Omaha Corp",
    state: "VA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AK",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AL",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AR",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "AZ",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CO",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "CT",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DC",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "DE",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "FL",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "GA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "HI",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ID",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IL",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "IN",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KS",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "KY",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "LA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MD",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ME",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MI",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MN",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MO",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MS",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "MT",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NC",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "ND",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NE",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NH",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NJ",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NM",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NV",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "NY",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OH",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OK",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "OR",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "PA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "RI",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SC",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "SD",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TN",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "TX",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "UT",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "VT",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WA",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WI",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WV",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "CSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "CSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "DSNP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "DSNP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "MA",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "MA",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "PDP",
    status: "Y",
    planYear: 2023,
    isSelfAttested: "FALSE",
  },
  {
    producerId: "620000",
    businessUnit: "PRE",
    carrier: "UnitedHealthcare",
    state: "WY",
    planType: "PDP",
    status: "Y",
    planYear: 2024,
    isSelfAttested: "FALSE",
  },
];
