name: Add Copilot Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronized]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add Copilot as a reviewer
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "copilot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}