name: Greetings

on:
  pull_request_target:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for opening your first issue!
            Please make sure to include a clear description of the problem, steps to reproduce, and any relevant code snippets. We'll do our best to assist you!
          pr-message: |
            Congratulations on opening your first pull request!
            Please ensure that your code follows our guidelines and includes relevant tests. We'll review your changes and provide feedback soon!
